// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listVariantDeploys = `-- name: ListVariantDeploys :many
SELECT mode, variant, cluster_url, cluster_token FROM variant_deployments WHERE mode = $1
`

func (q *Queries) ListVariantDeploys(ctx context.Context, mode pgtype.Text) ([]VariantDeployment, error) {
	rows, err := q.db.Query(ctx, listVariantDeploys, mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantDeployment
	for rows.Next() {
		var i VariantDeployment
		if err := rows.Scan(
			&i.Mode,
			&i.Variant,
			&i.ClusterUrl,
			&i.ClusterToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
