# purpose of the below commands are to create different layer change sets.
# covers following cases:
# - layer deleting directory with children
# - re-adding prevously deleted directory structure
#   spanning over multiple layers.
# - changing file contents in different layer
#
FROM alpine
WORKDIR /
COPY . .
RUN rm -rf /a/b
RUN mkdir -p /a/b/c
RUN echo "file2" >> /a/b/file2
RUN echo "file3" >> /a/b/c/file3
RUN rm /a/file1
RUN echo "changed" > /a/b/file2
