# Explorer Platform, a platform for hosting and discovering Minecraft servers.
# Copyright (C) 2024 Yannic Rieger <oss@76k.io>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# purpose of the below commands are to create different layer change sets.
# covers following cases:
# - layer deleting directory with children
# - re-adding prevously deleted directory structure
#   spanning over multiple layers.
# - changing file contents in different layer
#
FROM alpine
WORKDIR /
COPY . .
RUN rm -rf /a/b
RUN mkdir -p /a/b/c
RUN echo "file2" >> /a/b/file2
RUN echo "file3" >> /a/b/c/file3
RUN rm /a/file1
RUN echo "changed" > /a/b/file2
