// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SchemaMigration struct {
	Version string
}

type VariantDeployment struct {
	Mode         pgtype.Text
	Variant      pgtype.Text
	ClusterUrl   pgtype.Text
	ClusterToken pgtype.Text
}
