// Code generated by mockery. DO NOT EDIT.

package ptpnat

import (
	mock "github.com/stretchr/testify/mock"

	types100 "github.com/containernetworking/cni/pkg/types/100"
)

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// AllocIPs provides a mock function with given fields: plugin, stdinData
func (_m *MockHandler) AllocIPs(plugin string, stdinData []byte) ([]*types100.IPConfig, error) {
	ret := _m.Called(plugin, stdinData)

	if len(ret) == 0 {
		panic("no return value specified for AllocIPs")
	}

	var r0 []*types100.IPConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []byte) ([]*types100.IPConfig, error)); ok {
		return rf(plugin, stdinData)
	}
	if rf, ok := ret.Get(0).(func(string, []byte) []*types100.IPConfig); ok {
		r0 = rf(plugin, stdinData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types100.IPConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []byte) error); ok {
		r1 = rf(plugin, stdinData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandler_AllocIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllocIPs'
type MockHandler_AllocIPs_Call struct {
	*mock.Call
}

// AllocIPs is a helper method to define mock.On call
//   - plugin string
//   - stdinData []byte
func (_e *MockHandler_Expecter) AllocIPs(plugin interface{}, stdinData interface{}) *MockHandler_AllocIPs_Call {
	return &MockHandler_AllocIPs_Call{Call: _e.mock.On("AllocIPs", plugin, stdinData)}
}

func (_c *MockHandler_AllocIPs_Call) Run(run func(plugin string, stdinData []byte)) *MockHandler_AllocIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockHandler_AllocIPs_Call) Return(_a0 []*types100.IPConfig, _a1 error) *MockHandler_AllocIPs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandler_AllocIPs_Call) RunAndReturn(run func(string, []byte) ([]*types100.IPConfig, error)) *MockHandler_AllocIPs_Call {
	_c.Call.Return(run)
	return _c
}

// AttachDNATBPF provides a mock function with given fields: ifaceName
func (_m *MockHandler) AttachDNATBPF(ifaceName string) error {
	ret := _m.Called(ifaceName)

	if len(ret) == 0 {
		panic("no return value specified for AttachDNATBPF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ifaceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandler_AttachDNATBPF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachDNATBPF'
type MockHandler_AttachDNATBPF_Call struct {
	*mock.Call
}

// AttachDNATBPF is a helper method to define mock.On call
//   - ifaceName string
func (_e *MockHandler_Expecter) AttachDNATBPF(ifaceName interface{}) *MockHandler_AttachDNATBPF_Call {
	return &MockHandler_AttachDNATBPF_Call{Call: _e.mock.On("AttachDNATBPF", ifaceName)}
}

func (_c *MockHandler_AttachDNATBPF_Call) Run(run func(ifaceName string)) *MockHandler_AttachDNATBPF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHandler_AttachDNATBPF_Call) Return(_a0 error) *MockHandler_AttachDNATBPF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_AttachDNATBPF_Call) RunAndReturn(run func(string) error) *MockHandler_AttachDNATBPF_Call {
	_c.Call.Return(run)
	return _c
}

// AttachSNATBPF provides a mock function with given fields: nsPath, ifaceName
func (_m *MockHandler) AttachSNATBPF(nsPath string, ifaceName string) error {
	ret := _m.Called(nsPath, ifaceName)

	if len(ret) == 0 {
		panic("no return value specified for AttachSNATBPF")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(nsPath, ifaceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandler_AttachSNATBPF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachSNATBPF'
type MockHandler_AttachSNATBPF_Call struct {
	*mock.Call
}

// AttachSNATBPF is a helper method to define mock.On call
//   - nsPath string
//   - ifaceName string
func (_e *MockHandler_Expecter) AttachSNATBPF(nsPath interface{}, ifaceName interface{}) *MockHandler_AttachSNATBPF_Call {
	return &MockHandler_AttachSNATBPF_Call{Call: _e.mock.On("AttachSNATBPF", nsPath, ifaceName)}
}

func (_c *MockHandler_AttachSNATBPF_Call) Run(run func(nsPath string, ifaceName string)) *MockHandler_AttachSNATBPF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockHandler_AttachSNATBPF_Call) Return(_a0 error) *MockHandler_AttachSNATBPF_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_AttachSNATBPF_Call) RunAndReturn(run func(string, string) error) *MockHandler_AttachSNATBPF_Call {
	_c.Call.Return(run)
	return _c
}

// ConfigureSNAT provides a mock function with given fields: ifaceName
func (_m *MockHandler) ConfigureSNAT(ifaceName string) error {
	ret := _m.Called(ifaceName)

	if len(ret) == 0 {
		panic("no return value specified for ConfigureSNAT")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ifaceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandler_ConfigureSNAT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfigureSNAT'
type MockHandler_ConfigureSNAT_Call struct {
	*mock.Call
}

// ConfigureSNAT is a helper method to define mock.On call
//   - ifaceName string
func (_e *MockHandler_Expecter) ConfigureSNAT(ifaceName interface{}) *MockHandler_ConfigureSNAT_Call {
	return &MockHandler_ConfigureSNAT_Call{Call: _e.mock.On("ConfigureSNAT", ifaceName)}
}

func (_c *MockHandler_ConfigureSNAT_Call) Run(run func(ifaceName string)) *MockHandler_ConfigureSNAT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHandler_ConfigureSNAT_Call) Return(_a0 error) *MockHandler_ConfigureSNAT_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_ConfigureSNAT_Call) RunAndReturn(run func(string) error) *MockHandler_ConfigureSNAT_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAndConfigureVethPair provides a mock function with given fields: netNS, ips
func (_m *MockHandler) CreateAndConfigureVethPair(netNS string, ips []*types100.IPConfig) (string, string, error) {
	ret := _m.Called(netNS, ips)

	if len(ret) == 0 {
		panic("no return value specified for CreateAndConfigureVethPair")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, []*types100.IPConfig) (string, string, error)); ok {
		return rf(netNS, ips)
	}
	if rf, ok := ret.Get(0).(func(string, []*types100.IPConfig) string); ok {
		r0 = rf(netNS, ips)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, []*types100.IPConfig) string); ok {
		r1 = rf(netNS, ips)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string, []*types100.IPConfig) error); ok {
		r2 = rf(netNS, ips)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockHandler_CreateAndConfigureVethPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAndConfigureVethPair'
type MockHandler_CreateAndConfigureVethPair_Call struct {
	*mock.Call
}

// CreateAndConfigureVethPair is a helper method to define mock.On call
//   - netNS string
//   - ips []*types100.IPConfig
func (_e *MockHandler_Expecter) CreateAndConfigureVethPair(netNS interface{}, ips interface{}) *MockHandler_CreateAndConfigureVethPair_Call {
	return &MockHandler_CreateAndConfigureVethPair_Call{Call: _e.mock.On("CreateAndConfigureVethPair", netNS, ips)}
}

func (_c *MockHandler_CreateAndConfigureVethPair_Call) Run(run func(netNS string, ips []*types100.IPConfig)) *MockHandler_CreateAndConfigureVethPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]*types100.IPConfig))
	})
	return _c
}

func (_c *MockHandler_CreateAndConfigureVethPair_Call) Return(_a0 string, _a1 string, _a2 error) *MockHandler_CreateAndConfigureVethPair_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockHandler_CreateAndConfigureVethPair_Call) RunAndReturn(run func(string, []*types100.IPConfig) (string, string, error)) *MockHandler_CreateAndConfigureVethPair_Call {
	_c.Call.Return(run)
	return _c
}

// DeallocIPs provides a mock function with given fields: plugin, stdinData
func (_m *MockHandler) DeallocIPs(plugin string, stdinData []byte) error {
	ret := _m.Called(plugin, stdinData)

	if len(ret) == 0 {
		panic("no return value specified for DeallocIPs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(plugin, stdinData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandler_DeallocIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeallocIPs'
type MockHandler_DeallocIPs_Call struct {
	*mock.Call
}

// DeallocIPs is a helper method to define mock.On call
//   - plugin string
//   - stdinData []byte
func (_e *MockHandler_Expecter) DeallocIPs(plugin interface{}, stdinData interface{}) *MockHandler_DeallocIPs_Call {
	return &MockHandler_DeallocIPs_Call{Call: _e.mock.On("DeallocIPs", plugin, stdinData)}
}

func (_c *MockHandler_DeallocIPs_Call) Run(run func(plugin string, stdinData []byte)) *MockHandler_DeallocIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *MockHandler_DeallocIPs_Call) Return(_a0 error) *MockHandler_DeallocIPs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandler_DeallocIPs_Call) RunAndReturn(run func(string, []byte) error) *MockHandler_DeallocIPs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
